<<<<<<< HEAD
services:
  - type: web
    name: khadija-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
=======
services:
  - type: web
    name: khadija-flask-portfolio
    env: python
    buildCommand: ""
    startCommand: "python app.py"
>>>>>>> 8ee23484d07ce29cd3a272976b1d0e3b628b461c
